import {
  sampleItineraryDayRecord,
  samplePortRecord,
  sampleSailingRecord,
  sampleShipRecord,
} from "../data/sampleSchemaData";

const confidence = {
  confidence: "medium" as const,
  reviewStatus: "needs_user_review" as const,
  sourceType: "researched" as const,
  sourceSummary: "Fixture data for enrichment return tests.",
  lastReviewedAt: null,
  refreshRecommended: true,
  refreshReason: "Review before travel.",
  validFrom: null,
  validUntil: null,
};

export function sailingShellEnrichmentReturn(summary = "Planning context that does not confirm operational timing.") {
  return {
    schema: "complete-cruising-sailing-shell-enrichment-v1",
    schemaVersion: 1,
    sourceApp: "ChatGPT",
    generatedAt: "2026-06-28T12:30:00+01:00",
    target: {
      sailingId: sampleSailingRecord.id,
      sailingName: sampleSailingRecord.name,
      shipName: sampleShipRecord.name,
      cruiseLineName: "Princess Cruises",
    },
    provenance: { userEnteredFieldsUsed: ["sailing.id"] },
    enrichmentRun: {
      id: "enrichment-run-sailing-shell-test",
      name: "Sailing shell enrichment",
      targetType: "sailing",
      targetName: sampleSailingRecord.name,
      enrichmentPackType: "sailing_shell_enrichment",
      status: "generated",
      sourceTypesUsed: ["user_entered", "inferred"],
      validationWarnings: ["Do not treat this enrichment as booking confirmation."],
      notes: "Sailing-level context only.",
    },
    sailingEnrichment: { planningSummary: "Context only." },
    sections: [{
      id: "section-sailing-shell-test",
      parentType: "sailing",
      parentId: sampleSailingRecord.id,
      sectionType: "sailing_planning_summary",
      title: "Sailing planning summary",
      shortSummary: summary,
      structuredFacts: [{ label: "Planning status", value: "Needs review", origin: "inferred" }],
      practicalGuidance: ["Keep protected fields unchanged."],
      familyRelevance: ["Useful for route planning."],
      watchouts: ["No port times are confirmed."],
      suggestedNextActions: ["Verify Princess material before day planning."],
      confidence: {
        ...confidence,
        sourceType: "inferred",
        sourceSummary: "Generated from a local sailing shell.",
      },
    }],
    importAdvice: {
      safeToImport: true,
      requiresUserReview: true,
      protectedFieldWarnings: ["This JSON must not overwrite voyage code, sailing dates, itinerary rows or port times."],
      recommendedImportType: "sailing_shell",
    },
  };
}

export function itineraryVerificationReturn() {
  return {
    schema: "complete-cruising-itinerary-verification-v1",
    schemaVersion: 1,
    sourceApp: "ChatGPT",
    generatedAt: "2026-06-29T09:00:00+01:00",
    target: {
      sailingId: sampleSailingRecord.id,
      sailingName: sampleSailingRecord.name,
    },
    provenance: { userEnteredFieldsUsed: ["itineraryDays"] },
    verificationSummary: {
      overallStatus: "needs_review",
      summary: "One Naples timing needs confirmation.",
      majorWarnings: ["Port timings remain reviewable until checked against the cruise line."],
      minorWarnings: ["Day titles should remain aligned with reusable port records."],
      missingInformation: ["Tender status remains unknown."],
    },
    dayFindings: [{
      dayNumber: sampleItineraryDayRecord.dayNumber,
      date: sampleItineraryDayRecord.date,
      currentDayType: sampleItineraryDayRecord.dayType,
      currentPortName: samplePortRecord.name,
      status: "needs_review",
      findings: ["Local return buffer should reflect the revised arrival time."],
      suggestedCorrections: [
        {
          field: "arrivalTime",
          currentValue: sampleItineraryDayRecord.arrivalTime,
          suggestedValue: "07:15",
          reason: "Fixture timing review.",
          origin: "researched",
          confidence,
        },
        {
          field: "allAboardTime",
          currentValue: sampleItineraryDayRecord.allAboardTime,
          suggestedValue: "17:45",
          reason: "Fixture timing review.",
          origin: "researched",
          confidence,
        },
      ],
      refreshRecommended: true,
      refreshReason: "Operational timings should be checked again closer to sailing.",
    }],
    proposedImport: {
      updatesProtectedFields: true,
      protectedFieldWarnings: ["Arrival and all-aboard times are protected until the user confirms the overwrite."],
      recommendedAction: "import_after_confirmation",
      notes: "Review protected timing changes carefully.",
    },
  };
}

export function shipPackEnrichmentReturn() {
  return {
    schema: "complete-cruising-ship-pack-enrichment-v1",
    schemaVersion: 1,
    sourceApp: "ChatGPT",
    generatedAt: "2026-06-29T09:30:00+01:00",
    target: {
      shipId: sampleShipRecord.id,
      shipName: sampleShipRecord.name,
      cruiseLineName: "Princess Cruises",
      sailingId: sampleSailingRecord.id,
    },
    pack: {
      packType: "ship_dining",
      title: "Ship dining",
      scope: ["Ship", "Optional sailing context"],
      exclusions: ["No itinerary-day guidance"],
    },
    provenance: { researchedFields: ["dining"] },
    enrichmentRun: {
      id: "enrichment-run-ship-pack-test",
      name: "Ship dining enrichment",
      targetType: "ship",
      targetName: sampleShipRecord.name,
      enrichmentPackType: "ship_dining",
      status: "generated",
      sourceTypesUsed: ["researched"],
      validationWarnings: ["Dining venues and hours still need user review."],
      notes: "Ship pack fixture.",
    },
    section: {
      id: "section-ship-pack-test",
      parentType: "ship",
      parentId: sampleShipRecord.id,
      sectionType: "ship_dining",
      title: "Dining guide",
      shortSummary: "A selective dining overview for careful onboard choices.",
      structuredFacts: [{ label: "Focus", value: "Review-led dining options", origin: "researched" }],
      practicalGuidance: ["Treat the first evening as a light orientation pass."],
      familyRelevance: ["Keep one easy Seb-safe option in reserve."],
      watchouts: ["Opening patterns may shift before sailing."],
      suggestedNextActions: ["Confirm key dining venues before travel."],
      confidence,
    },
    shipPatchProposal: {
      safeNonProtectedUpdates: {},
      protectedUpdates: {},
      protectedFieldWarnings: ["Ship identity remains protected in this import path."],
      notes: "Run and section only.",
    },
    importAdvice: {
      safeToImport: true,
      requiresUserReview: true,
      recommendedImportType: "ship_enrichment",
    },
  };
}

export function portPackEnrichmentReturn() {
  return {
    schema: "complete-cruising-port-pack-enrichment-v1",
    schemaVersion: 1,
    sourceApp: "ChatGPT",
    generatedAt: "2026-06-29T10:00:00+01:00",
    target: {
      portId: samplePortRecord.id,
      portName: samplePortRecord.name,
      countryName: "Italy",
      sailingId: sampleSailingRecord.id,
      itineraryDayId: sampleItineraryDayRecord.id,
    },
    pack: {
      packType: "port_cruise_logistics",
      title: "Cruise logistics",
      scope: ["Reusable port record"],
      exclusions: ["No selected shore plan"],
    },
    provenance: { researchedFields: ["logistics"] },
    enrichmentRun: {
      id: "enrichment-run-port-pack-test",
      name: "Port logistics enrichment",
      targetType: "port",
      targetName: samplePortRecord.name,
      enrichmentPackType: "port_cruise_logistics",
      status: "generated",
      sourceTypesUsed: ["researched"],
      validationWarnings: ["Terminal details should be refreshed before travel."],
      notes: "Port pack fixture.",
    },
    section: {
      id: "section-port-pack-test",
      parentType: "port",
      parentId: samplePortRecord.id,
      sectionType: "port_cruise_logistics",
      title: "Cruise logistics",
      shortSummary: "A cautious logistics summary for the reusable port record.",
      structuredFacts: [{ label: "Docking", value: "Review before sailing", origin: "researched" }],
      practicalGuidance: ["Keep a time buffer before returning to the ship."],
      familyRelevance: ["Choose the lowest-stress route back to the terminal."],
      watchouts: ["Traffic and embarkation queues can change."],
      suggestedNextActions: ["Refresh terminal detail closer to the cruise."],
      confidence,
    },
    attractionProposals: [{
      name: "Historic centre",
      type: "landmark",
      shortDescription: "A flexible city-centre wander.",
      whyItMatters: "Useful for a low-friction first pass ashore.",
      distanceFromPortText: "Walkable",
      travelTimeFromPortText: "15 minutes",
      typicalVisitDuration: "60 to 90 minutes",
      bookingRequired: "not_required",
      costLevel: "free",
      familySuitability: "good",
      sebInterestScore: 3,
      parentInterestScore: 4,
      weatherSensitivity: "medium",
      accessibilityNotes: "Check paving and gradients locally.",
      photoPrompt: "Frame the harbour and city edge together.",
      confidence,
    }],
    portPatchProposal: {
      safeNonProtectedUpdates: {},
      protectedUpdates: {},
      protectedFieldWarnings: ["Reusable port identity fields remain protected in this import path."],
      notes: "Run and section only.",
    },
    importAdvice: {
      safeToImport: true,
      requiresUserReview: true,
      recommendedImportType: "port_enrichment",
    },
  };
}

export function dayGuideGenerationReturn() {
  return {
    schema: "complete-cruising-day-guide-generation-v1",
    schemaVersion: 1,
    sourceApp: "ChatGPT",
    generatedAt: "2026-06-29T10:30:00+01:00",
    target: {
      sailingId: sampleSailingRecord.id,
      sailingName: sampleSailingRecord.name,
      itineraryDayId: sampleItineraryDayRecord.id,
      dayNumber: sampleItineraryDayRecord.dayNumber,
      date: sampleItineraryDayRecord.date,
      dayType: "port",
      portName: samplePortRecord.name,
    },
    provenance: { researchedFields: ["day guide"] },
    dayGuide: {
      id: "day-guide-naples-return",
      itineraryDayId: sampleItineraryDayRecord.id,
      title: "Naples: a careful first pass",
      todayAtAGlance: {
        location: "Naples",
        arrivalTime: "07:00",
        departureTime: "18:00",
        allAboardTime: "17:30",
        latestSafeReturnTime: "16:45",
        weatherSummary: "Warm and dry",
        localLanguage: "Italian",
        localCurrency: "Euro (EUR)",
      },
      whatMattersToday: ["Heat and traffic both matter for the return buffer."],
      likelyPlanSummary: "Historic centre, harbour edge and a calm pizza stop.",
      backupPlanSummary: "Stay closer to the port if timings tighten.",
      takeAshore: ["Cruise cards", "Phone", "Water"],
      sebDiscovery: {
        flag: null,
        localPhrase: "Buongiorno",
        pronunciationHint: "bwon-jor-noh",
        geographyFact: "Naples sits beside the Bay of Naples beneath Vesuvius.",
        thingToSpot: "Look for Vesuvius beyond the harbour.",
        quizQuestion: "Which volcano shaped Pompeii's story?",
        quizAnswer: "Vesuvius",
      },
      photoPrompt: "Capture the harbour with Vesuvius if the skyline is clear.",
      returnBufferAdvice: "Aim to be heading back well before the late afternoon rush.",
      confidenceNotes: ["All timings still need user review before travel."],
      generatedFrom: ["Local sailing shell", "Reusable port context"],
      confidence,
    },
    operationalWarnings: ["Keep protected sailing times under user control."],
    memoryPrompt: {
      prompt: "What felt most alive about Naples today?",
      sebFavouritePrompt: "What did Seb like best?",
      photoPrompt: "Which frame best held the day?",
      adventureAlmanacHint: "Keep one detail that will still matter later.",
    },
    importAdvice: {
      safeToImport: true,
      requiresUserReview: true,
      protectedFieldWarnings: ["Protected itinerary timings remain review-led."],
      recommendedImportType: "day_guide",
    },
  };
}

export function shorePlanGenerationReturn() {
  return {
    schema: "complete-cruising-shore-plan-generation-v1",
    schemaVersion: 1,
    sourceApp: "ChatGPT",
    generatedAt: "2026-06-29T11:00:00+01:00",
    target: {
      sailingId: sampleSailingRecord.id,
      sailingName: sampleSailingRecord.name,
      itineraryDayId: sampleItineraryDayRecord.id,
      dayNumber: sampleItineraryDayRecord.dayNumber,
      date: sampleItineraryDayRecord.date,
      portId: samplePortRecord.id,
      portName: samplePortRecord.name,
    },
    provenance: { researchedFields: ["shore plan"] },
    planningAssumptions: [{
      assumption: "Traffic may slow the late return into the port area.",
      origin: "researched",
      confidence,
    }],
    shorePlans: [
      {
        id: "shore-plan-return-balanced",
        itineraryDayId: sampleItineraryDayRecord.id,
        portId: samplePortRecord.id,
        name: "Balanced Naples wander",
        planType: "low_effort",
        status: "shortlisted",
        summary: "A harbour-to-historic-centre walk with a simple lunch stop.",
        startTime: "08:30",
        endTime: "15:45",
        latestSafeReturnTime: "16:30",
        transportMode: "walk",
        attractionNames: ["Historic centre"],
        estimatedTravelTimeText: "15 minutes on foot to the first stop",
        returnBufferMinutes: 60,
        riskLevel: "medium",
        weatherDependency: "medium",
        familySuitability: "good",
        sebSuitabilityNotes: "Good for geography spotting without overloading the day.",
        costNotes: "Mostly free apart from food and optional taxis.",
        bookingReference: null,
        whatToTake: ["Water", "Cruise cards"],
        watchouts: ["Heat builds quickly in the late morning."],
        confidence,
      },
      {
        id: "shore-plan-return-backup",
        itineraryDayId: sampleItineraryDayRecord.id,
        portId: samplePortRecord.id,
        name: "Short harbour fallback",
        planType: "backup",
        status: "idea",
        summary: "A shorter loop close to the port if energy or timings drop.",
        startTime: "09:00",
        endTime: "13:30",
        latestSafeReturnTime: "15:30",
        transportMode: "walk",
        attractionNames: ["Harbour edge"],
        estimatedTravelTimeText: "10 minutes on foot",
        returnBufferMinutes: 90,
        riskLevel: "low",
        weatherDependency: "low",
        familySuitability: "excellent",
        sebSuitabilityNotes: "Keeps the day lighter while still giving Seb something real to notice.",
        costNotes: "Low-cost fallback.",
        bookingReference: null,
        whatToTake: ["Water", "Phone"],
        watchouts: ["Keep shade breaks in mind."],
        confidence,
      },
    ],
    recommendation: {
      recommendedPlanId: "shore-plan-return-balanced",
      reason: "It balances discovery, food and a manageable return.",
      backupPlanId: "shore-plan-return-backup",
      returnToShipAdvice: "Treat the latest safe return as firm even if the city still feels lively.",
    },
    importAdvice: {
      safeToImport: true,
      requiresUserReview: true,
      protectedFieldWarnings: ["Selected and backup plan links stay under user control."],
      recommendedImportType: "shore_plan",
    },
  };
}
