import { z } from "zod";
import { AuditMetadataSchema, ConfidenceMetadataSchema, IdSchema, SailingStatusSchema, VisualMetadataSchema } from "./commonSchemas";

export const CabinSchema = z.object({ id: IdSchema, sailingId: IdSchema, cabinNumber: z.string().optional(), cabinType: z.string().optional(), deck: z.string().optional(), locationDescriptor: z.string().optional(), balcony: z.boolean().optional(), cabinNotes: z.string().optional(), audit: AuditMetadataSchema, confidence: ConfidenceMetadataSchema.optional() }).strict();
export const TravellerSchema = z.object({ id: IdSchema, displayName: z.string().min(1), travellerType: z.enum(["adult", "child", "family_member", "guest"]), sailingIds: z.array(IdSchema).optional(), preferences: z.record(z.string(), z.unknown()).optional(), notes: z.string().optional(), audit: AuditMetadataSchema }).strict();
export const SailingSchema = z.object({
  id: IdSchema, name: z.string().min(1), cruiseLineId: IdSchema, shipId: IdSchema, status: SailingStatusSchema, departureDate: z.string().date(), returnDate: z.string().date(), voyageCode: z.string().min(1).optional(), routeSummary: z.string().min(1).optional(), notes: z.string().optional(), embarkationPortId: IdSchema.optional(), disembarkationPortId: IdSchema.optional(), cabinId: IdSchema.optional(), travellerIds: z.array(IdSchema).optional(), packageNotes: z.string().optional(), diningNotes: z.string().optional(), transferNotes: z.string().optional(), planningSummary: z.string().optional(), enrichmentStatus: z.enum(["not_started", "partial", "enriched", "needs_refresh", "complete"]).optional(), activeDayId: IdSchema.optional(), visual: VisualMetadataSchema.optional(), audit: AuditMetadataSchema, confidence: ConfidenceMetadataSchema.optional(), sampleOnly: z.boolean().optional(), dataCaveat: z.string().min(1).optional(),
}).strict().refine(({ departureDate, returnDate }) => departureDate <= returnDate, { message: "returnDate must not be earlier than departureDate", path: ["returnDate"] });

export const DocumentItemSchema = z.object({ id: IdSchema, sailingId: IdSchema, label: z.string().min(1), status: z.enum(["not_started", "in_progress", "ready", "not_applicable"]), notes: z.string().optional(), audit: AuditMetadataSchema }).strict();
export const FamilyNoteSchema = z.object({ id: IdSchema, sailingId: IdSchema, itineraryDayId: IdSchema.optional(), note: z.string().min(1), confidence: ConfidenceMetadataSchema.optional(), audit: AuditMetadataSchema }).strict();
export const AppSettingSchema = z.object({ id: IdSchema, key: z.string().min(1), value: z.unknown(), audit: AuditMetadataSchema }).strict();
