import { z } from "zod";
import {
  AuditMetadataSchema,
  ConfidenceMetadataSchema,
  IdSchema,
  SourceTypeSchema,
  WeatherContextSchema,
  WeatherRefreshStateSchema,
  WeatherSnapshotTypeSchema,
  WeatherStateSchema,
} from "./commonSchemas";

export const WeatherSnapshotSchema = z.object({
  id: IdSchema,
  sailingId: IdSchema,
  itineraryDayId: IdSchema,
  portId: IdSchema.optional(),
  date: z.string().date(),
  latitude: z.number().min(-90).max(90),
  longitude: z.number().min(-180).max(180),
  sourceName: z.string().min(1),
  sourceUrl: z.string().url().optional(),
  sourceAttribution: z.string().min(1).optional(),
  sourceType: SourceTypeSchema,
  snapshotType: WeatherSnapshotTypeSchema,
  weatherState: WeatherStateSchema,
  weatherContext: WeatherContextSchema.optional(),
  capturedAt: z.string().datetime({ offset: true }),
  generatedAt: z.string().datetime({ offset: true }).optional(),
  observedAt: z.string().datetime({ offset: true }).optional(),
  validFrom: z.string().date(),
  validUntil: z.string().date(),
  lastRefreshAttemptAt: z.string().datetime({ offset: true }).optional(),
  visitDate: z.string().date().optional(),
  forecastDate: z.string().date().optional(),
  forecastExpectedFrom: z.string().date().optional(),
  isVisitDateForecast: z.boolean().optional(),
  satisfiesVisitForecastReadiness: z.boolean().optional(),
  refreshState: WeatherRefreshStateSchema,
  refreshRecommended: z.boolean(),
  refreshReason: z.string().trim().min(1).optional(),
  refreshError: z.string().trim().min(1).optional(),
  conditionSummary: z.string().min(1),
  temperatureHighC: z.number().min(-100).max(70).optional(),
  temperatureLowC: z.number().min(-100).max(70).optional(),
  temperatureCurrentC: z.number().min(-100).max(70).optional(),
  apparentTemperatureC: z.number().min(-100).max(70).optional(),
  precipitationChance: z.number().min(0).max(100).optional(),
  precipitationMm: z.number().min(0).optional(),
  windSpeedKph: z.number().min(0).optional(),
  windGustKph: z.number().min(0).optional(),
  humidity: z.number().min(0).max(100).optional(),
  uvIndex: z.number().min(0).optional(),
  sunrise: z.string().datetime({ offset: true }).optional(),
  sunset: z.string().datetime({ offset: true }).optional(),
  comfortSummary: z.string().min(1),
  clothingGuidance: z.string().min(1),
  planImpact: z.string().min(1),
  confidence: ConfidenceMetadataSchema,
  audit: AuditMetadataSchema,
  sampleOnly: z.boolean().optional(),
  dataCaveat: z.string().min(1).optional(),
}).strict();

export const WeatherSnapshotReviewEventSchema = z.object({
  id: IdSchema,
  sailingId: IdSchema,
  itineraryDayId: IdSchema,
  forecastDate: z.string().date(),
  action: z.enum([
    "preferred_snapshot_selected",
    "conflict_acknowledged",
    "snapshot_rejected",
    "preferred_snapshot_restored",
  ]),
  fromSnapshotId: IdSchema.optional(),
  toSnapshotId: IdSchema.optional(),
  candidateSnapshotIds: z.array(IdSchema),
  reason: z.string().trim().min(1).optional(),
  notes: z.string().trim().min(1).optional(),
  createdAt: z.string().datetime({ offset: true }),
  createdBy: z.enum(["user", "system"]),
}).strict();
