import { z } from "zod";
import {
  AuditMetadataSchema,
  ConfidenceMetadataSchema,
  IdSchema,
  SourceTypeSchema,
  WeatherRefreshStateSchema,
  WeatherSnapshotTypeSchema,
  WeatherStateSchema,
} from "./commonSchemas";

export const WeatherSnapshotSchema = z.object({
  id: IdSchema,
  sailingId: IdSchema,
  itineraryDayId: IdSchema,
  portId: IdSchema.optional(),
  date: z.string().date(),
  latitude: z.number().min(-90).max(90),
  longitude: z.number().min(-180).max(180),
  sourceName: z.string().min(1),
  sourceUrl: z.string().url().optional(),
  sourceType: SourceTypeSchema,
  snapshotType: WeatherSnapshotTypeSchema,
  weatherState: WeatherStateSchema,
  capturedAt: z.string().datetime({ offset: true }),
  validFrom: z.string().date(),
  validUntil: z.string().date(),
  lastRefreshAttemptAt: z.string().datetime({ offset: true }).optional(),
  refreshState: WeatherRefreshStateSchema,
  refreshRecommended: z.boolean(),
  refreshReason: z.string().trim().min(1).optional(),
  refreshError: z.string().trim().min(1).optional(),
  conditionSummary: z.string().min(1),
  temperatureHighC: z.number().min(-100).max(70).optional(),
  temperatureLowC: z.number().min(-100).max(70).optional(),
  precipitationChance: z.number().min(0).max(100).optional(),
  precipitationMm: z.number().min(0).optional(),
  windSpeedKph: z.number().min(0).optional(),
  windGustKph: z.number().min(0).optional(),
  uvIndex: z.number().min(0).optional(),
  sunrise: z.string().datetime({ offset: true }).optional(),
  sunset: z.string().datetime({ offset: true }).optional(),
  comfortSummary: z.string().min(1),
  clothingGuidance: z.string().min(1),
  planImpact: z.string().min(1),
  confidence: ConfidenceMetadataSchema,
  audit: AuditMetadataSchema,
  sampleOnly: z.boolean().optional(),
  dataCaveat: z.string().min(1).optional(),
}).strict();
